env:
  global:
    - CC_TEST_REPORTER_ID=350c818a2d0a419ad491d6eb139fbd59dea50ab91a8f4a7970f15e987f2b44ff

language: python
python: "3.5.5"

install:
  - "pip install -r requirements.txt"

before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter"
  - "chmod +x ./cc-test-reporter"
  - "./cc-test-reporter before-build"

script: "python3 manage.py compilemessages && coverage run manage.py test --parallel"

after_script:
  - "coverage xml"
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

notifications:
  slack: osisteam:2M3DtIOGE4clU1DF8r6k8NQD
services:
  - rabbitmq
addons:
    postgresql: "9.6"
